"""Core data structures and input readers for Induced-Moment Exchange Explorer."""

from .model import (
    ExchangeBond,
    MagneticCrystal,
    MagneticSite,
    UnitMetadata,
    ValidationReport,
)
from .reciprocal import (
    ExchangeEigenSystem,
    ExchangePathData,
    FourierExchangeResult,
    HermiticityReport,
    OrderingAnalysis,
    QPath,
    ReciprocalLattice,
    check_hermiticity,
    compute_jq,
    compute_ordering,
    compute_reciprocal_lattice,
    exchange_eigensystem,
    exchange_fourier,
    exchange_extrema,
    exchange_heatmap_data,
    fourier_exchange,
    fourier_transform,
    generate_q_mesh,
    high_symmetry_path,
    ordering_analysis,
    path_exchange_data,
    plot_exchange_path,
    q_mesh,
    reciprocal_lattice,
    reciprocal_mesh,
    regular_q_mesh,
)
from .induced import (
    InducedMomentResponse,
    InducedResponse,
    InducedResponseResult,
    SublatticeClassification,
    XInference,
    XInferenceResult,
    instantaneous_slave_moments,
)
from .downfolding import (
    DressedExchangeRealSpace,
    DownfoldingResult,
    EnergyEquivalence,
    InducedExchangeDownfolding,
    InducedMomentDownfolding,
    MryasovDownfolding,
    OrderingComparison,
    VariationalDownfolding,
    compute_downfolded_exchange,
    downfold_exchange,
    downfold_induced_exchange,
    inverse_dressed_exchange,
    inverse_fourier_dressed_jij,
    mryasov_downfold,
)
from .magnons import (
    FMSpinWaveResult,
    SpinStiffnessResult,
    compute_magnon_spectrum,
    construct_fm_dynamical_matrix,
    fit_spin_stiffness,
    fm_dynamical_matrix,
    fm_harmonic_matrix,
    fm_magnon_spectrum,
    magnon_spectrum,
    mryasov_fm_magnon_spectrum,
    magnon_path_data,
    plot_magnon_path,
    polesya_fm_magnon_spectrum,
    raw_fm_magnon_spectrum,
    robust_only_fm_magnon_spectrum,
    spin_stiffness,
    spin_wave_spectrum,
)
from .units import convert_energy, energy_conversion_factor, normalise_energy_unit
from .provenance import HAMILTONIAN_CONVENTION, K_APPROXIMATION, build_analysis_provenance
from .comparison import (
    DatasetAnalysis,
    DatasetComparison,
    DatasetCompatibility,
    ExchangeDataset,
    ExternalInducedResponse,
    InducedResponseComparison,
    OrderingSummary,
    RealSpaceExchangeData,
    ResponseMismatchMetrics,
    compare_datasets,
    compare_exchange_datasets,
    compare_induced_response,
    dataset_compatibility,
    export_comparison_csv,
    export_comparison_tables,
    load_external_induced_response,
    plot_comparison,
    plot_exchange_comparison,
    plot_induced_response_comparison,
    plot_real_space_comparison,
    plot_stiffness_comparison,
    predict_induced_response,
    validate_dataset_compatibility,
)

_IO_EXPORTS = {
    "InputFormatError",
    "InpsdConfig",
    "LoadedUppASD",
    "load_uppasd",
    "parse_exchange",
    "parse_inpsd",
    "parse_jfile",
    "parse_momfile",
    "parse_posfile",
    "parse_uppasd",
}


def __getattr__(name: str):
    # Lazy imports keep ``python -m induced_exchange.io_uppasd`` free of the
    # runpy warning caused by importing the module before executing it.
    if name in _IO_EXPORTS:
        from . import io_uppasd

        return getattr(io_uppasd, name)
    raise AttributeError(name)

__all__ = [
    "ExchangeBond",
    "InputFormatError",
    "InpsdConfig",
    "LoadedUppASD",
    "MagneticCrystal",
    "MagneticSite",
    "UnitMetadata",
    "ValidationReport",
    "InducedMomentResponse",
    "InducedResponse",
    "InducedResponseResult",
    "SublatticeClassification",
    "XInference",
    "XInferenceResult",
    "instantaneous_slave_moments",
    "DressedExchangeRealSpace",
    "DownfoldingResult",
    "EnergyEquivalence",
    "InducedExchangeDownfolding",
    "InducedMomentDownfolding",
    "MryasovDownfolding",
    "OrderingComparison",
    "VariationalDownfolding",
    "compute_downfolded_exchange",
    "downfold_exchange",
    "downfold_induced_exchange",
    "inverse_dressed_exchange",
    "inverse_fourier_dressed_jij",
    "mryasov_downfold",
    "FMSpinWaveResult",
    "SpinStiffnessResult",
    "compute_magnon_spectrum",
    "construct_fm_dynamical_matrix",
    "convert_energy",
    "energy_conversion_factor",
    "fit_spin_stiffness",
    "fm_dynamical_matrix",
    "fm_harmonic_matrix",
    "fm_magnon_spectrum",
    "magnon_spectrum",
    "mryasov_fm_magnon_spectrum",
    "magnon_path_data",
    "plot_magnon_path",
    "normalise_energy_unit",
    "HAMILTONIAN_CONVENTION",
    "K_APPROXIMATION",
    "build_analysis_provenance",
    "DatasetAnalysis",
    "DatasetComparison",
    "DatasetCompatibility",
    "ExchangeDataset",
    "ExternalInducedResponse",
    "InducedResponseComparison",
    "OrderingSummary",
    "RealSpaceExchangeData",
    "ResponseMismatchMetrics",
    "compare_datasets",
    "compare_exchange_datasets",
    "compare_induced_response",
    "dataset_compatibility",
    "export_comparison_csv",
    "export_comparison_tables",
    "load_external_induced_response",
    "plot_comparison",
    "plot_exchange_comparison",
    "plot_induced_response_comparison",
    "plot_real_space_comparison",
    "plot_stiffness_comparison",
    "predict_induced_response",
    "validate_dataset_compatibility",
    "polesya_fm_magnon_spectrum",
    "raw_fm_magnon_spectrum",
    "robust_only_fm_magnon_spectrum",
    "spin_stiffness",
    "spin_wave_spectrum",
    "ExchangeEigenSystem",
    "ExchangePathData",
    "FourierExchangeResult",
    "HermiticityReport",
    "OrderingAnalysis",
    "QPath",
    "ReciprocalLattice",
    "check_hermiticity",
    "compute_jq",
    "compute_ordering",
    "compute_reciprocal_lattice",
    "exchange_eigensystem",
    "exchange_fourier",
    "exchange_extrema",
    "exchange_heatmap_data",
    "fourier_exchange",
    "fourier_transform",
    "generate_q_mesh",
    "high_symmetry_path",
    "ordering_analysis",
    "path_exchange_data",
    "plot_exchange_path",
    "q_mesh",
    "reciprocal_lattice",
    "reciprocal_mesh",
    "regular_q_mesh",
    "load_uppasd",
    "parse_exchange",
    "parse_inpsd",
    "parse_jfile",
    "parse_momfile",
    "parse_posfile",
    "parse_uppasd",
]
